### ISSUE TITLE
FileNotFoundError， ValueError

### ISSUE THREAD

**Issue by BackMountainDevil** [soraxas/terminal-plot#2]
# version

- Python 3.10.13
- terminal-plot  2.1.0
- tensorboard                2.14.1
- tensorboard-data-server    0.7.1

event file existed. tensorboard wrok fine with firefox.

I tried not add \ in filepath, but got another err.

# err log

```bash
(310) [mifen@hp tmp]$ ls results/tb_logs/ippo_env\=8_adam_gae__jinan-1__2024-07-16_08-59-03/
events.out.tfevents.1721091543.amax

(310) [mifen@hp tmp]$ termplot 'results/tb_logs/ippo_env=8_adam_gae__jinan-1__2024-07-16_08-59-03/events.out.tfevents.1721091543.amax'
Traceback (most recent call last):
  File "/home/mifen/.conda/envs/310/bin/termplot", line 8, in <module>
    sys.exit(run())
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 481, in run
    main(_args)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 441, in main
    plot_logic(
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 370, in plot_logic
    _plot_for_one_run(plotter, figure_data, data_source.get_consolidated_stats(), i)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 312, in _plot_for_one_run
    x_val, y_val = figure_data.get_series(
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/data_source/tensorboard_source.py", line 73, in get_series
    wall_t, steps, vals = series.T
ValueError: too many values to unpack (expected 3)

(310) [mifen@hp tmp]$ termplot 'results/tb_logs/ippo_env\=8_adam_gae__jinan-1__2024-07-16_08-59-03/events.out.tfevents.1721091543.amax'
Traceback (most recent call last):
  File "/home/mifen/.conda/envs/310/bin/termplot", line 8, in <module>
    sys.exit(run())
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 481, in run
    main(_args)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 425, in main
    monitor = FilesystemMonitor(args.folder)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/fs_monitor.py", line 42, in __init__
    self.observer.start()
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/api.py", line 280, in start
    emitter.start()
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 125, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify_[events.out.tfevents.1721091543.zip](https://github.com/user-attachments/files/16262628/events.out.tfevents.1721091543.zip)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/api.py", line 280, in start
    emitter.start()
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 92, in start
    self.on_thread_start()
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 125, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive, event_mask)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 37, in __init__
    self._inotify = Inotify(path, recursive, event_mask)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 176, in __init__
    self._add_watch(path, event_mask)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 401, in _add_watch
    Inotify._raise_error()
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 417, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory

(310) [mifen@hp tmp]$ termplot 'results/tb_logs/'
Traceback (most recent call last):
  File "/home/mifen/.conda/envs/310/bin/termplot", line 8, in <module>
    sys.exit(run())
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 481, in run
    main(_args)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 441, in main
    plot_logic(
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 370, in plot_logic
    _plot_for_one_run(plotter, figure_data, data_source.get_consolidated_stats(), i)
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 312, in _plot_for_one_run
    x_val, y_val = figure_data.get_series(
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/data_source/tensorboard_source.py", line 73, in get_series
    wall_t, steps, vals = series.T
ValueError: too many values to unpack (expected 3)
(310) [mifen@hp tmp]$ 
```

**Comment by BackMountainDevil** [comment]
[events.out.tfevents.1721091543.zip](https://github.com/user-attachments/files/16262654/events.out.tfevents.1721091543.zip)

**Comment by BackMountainDevil** [comment]
use latest code

```bash
(310) [mifen@hp tmp]$ git clone https://github.com/soraxas/terminal-plot.git

(310) [mifen@hp tmp]$ pip uninstall terminal-plot
  Successfully uninstalled terminal-plot-2.1.0

(310) [mifen@hp tmp]$ pip install terminal-plot/ 
Successfully installed plotext-5.0.2 terminal-plot-2.1.0

(310) [mifen@hp tmp]$ termplot "results/tb_logs/ippo_env=8_adam_gae__jinan-1__2024-07-16_08-59-03/" --debug
Traceback (most recent call last):
  File "/home/mifen/.conda/envs/310/bin/termplot", line 5, in <module>
    from termplot.main import run
  File "/home/mifen/.conda/envs/310/lib/python3.10/site-packages/termplot/main.py", line 18, in <module>
    from termplot.monitor import AbstractMonitor
ModuleNotFoundError: No module named 'termplot.monitor'
```

**Comment by soraxas** [comment]
Thanks for reporting. The packaging issue should be fixed in `2.2.0` now.

```sh
pip install 'terminal-plot>=2.2.0'
```

```sh
$ termplot data/
```
![Screenshot from 2024-07-17 21-50-31](https://github.com/user-attachments/assets/58dedc87-ff61-4c07-a18b-74c57154a091)
```sh
$ termplot data/ -ccc
```
![Screenshot from 2024-07-17 21-50-44](https://github.com/user-attachments/assets/b0f04bec-ea03-4fcb-a074-95868cf8ccb8)

------

Normally I use it inside tmux, and with `termplot folder/ -ccc -f` to monitor its progress

**Comment by BackMountainDevil** [comment]
ModuleNotFoundError has been fixed at new version. New problem maybe font?

`termplot "ippo_env=8_adam_gae__jinan-1__2024-07-16_08-59-03"`

![图片](https://github.com/user-attachments/assets/ce5d1b85-7bb9-4d44-a4c5-3a42d4dc89db)

`termplot "ippo_env=8_adam_gae__jinan-1__2024-07-16_08-59-03" -ccc` 

![图片](https://github.com/user-attachments/assets/b6c5b8f0-4cfd-4c67-bf92-d9106de05a42)

![图片](https://github.com/user-attachments/assets/b615df26-3a61-4a4d-af56-a16dc3521d2d)

**Comment by soraxas** [comment]
This is the integrated terminal in vscode? Does it works on standalone terminal?

You'll have to figure out how to make vs code support the Unicode characters.

Something like this might help. https://dev.to/ri5hirajp/enable-unicode-support-in-vscode-terminal-2ph5

**Comment by BackMountainDevil** [comment]
It is vscode's terminal.

Same problem in Windows Terminal(Version: 1.6.10571.0)

try that solution part about change font name but same problem. Thanks for your kindly help.

**Comment by soraxas** [comment]
I see I didn't you are on WSL.

Installing nerdfont in windows terminal might help:
https://medium.com/@vedantkadam541/beautify-your-windows-terminal-using-nerd-fonts-and-oh-my-posh-4f4393f097

**Comment by BackMountainDevil** [comment]
Yes, not in wsl. It is a linux server. I tried install [nerd font](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/Hack.zip) and set "Hack Nerd Font" in vsc/win terminal, not work.

Thank you for you kindly help. Not going to dive into it.
